"""empty message

Revision ID: 3626dbde316a
Revises: 4f0c1e96faa6
Create Date: 2021-09-20 13:25:04.092001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3626dbde316a'
down_revision = '4f0c1e96faa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_imageURL_key', 'news', type_='unique')
    op.drop_constraint('news_pageURL_key', 'news', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('news_pageURL_key', 'news', ['pageURL'])
    op.create_unique_constraint('news_imageURL_key', 'news', ['imageURL'])
    # ### end Alembic commands ###
