"""empty message

Revision ID: b924dbce1cda
Revises: ba1221f520c4
Create Date: 2021-09-29 16:31:34.438156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b924dbce1cda'
down_revision = 'ba1221f520c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('imageURL', sa.String(length=300), nullable=False))
    op.add_column('event', sa.Column('pageURL', sa.String(length=300), nullable=False))
    op.add_column('event', sa.Column('users_like', sa.Integer(), nullable=True))
    op.drop_column('event', 'category')
    op.drop_column('event', 'description')
    op.drop_column('event', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('event', 'users_like')
    op.drop_column('event', 'pageURL')
    op.drop_column('event', 'imageURL')
    # ### end Alembic commands ###
