"""empty message

Revision ID: ba31b74d5d06
Revises: cb881bb2a0e2
Create Date: 2021-09-30 19:06:25.080882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba31b74d5d06'
down_revision = 'cb881bb2a0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discussion_comment_body_key', 'discussion_comment', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('discussion_comment_body_key', 'discussion_comment', ['body'])
    # ### end Alembic commands ###
