"""empty message

Revision ID: d25a7b4128f4
Revises: 13d449e74606
Create Date: 2021-09-30 00:02:24.660408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25a7b4128f4'
down_revision = '13d449e74606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'location',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('event', 'category',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'category',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('event', 'location',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
