"""empty message

Revision ID: ea52d56dbf5f
Revises: ebb149508c48
Create Date: 2021-09-27 23:36:02.424123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea52d56dbf5f'
down_revision = 'ebb149508c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discussion_comment_user_id_fkey', 'discussion_comment', type_='foreignkey')
    op.create_foreign_key(None, 'discussion_comment', 'user', ['user_id'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discussion_comment', type_='foreignkey')
    op.create_foreign_key('discussion_comment_user_id_fkey', 'discussion_comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
